"""empty message

Revision ID: 634fdd2bd607
Revises: 3557c92ab790
Create Date: 2024-01-21 18:50:40.057406

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "634fdd2bd607"
down_revision = "3557c92ab790"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
