"""empty message

Revision ID: e878ae66f154
Revises: 819cbf6e030b
Create Date: 2024-01-20 20:23:55.730916

"""
import sqlalchemy as sa
from alembic import op
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = "e878ae66f154"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("fullname", sa.String(length=30), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "email", sqlalchemy_utils.types.email.EmailType(length=255), nullable=True
        ),
        sa.Column(
            "password",
            sqlalchemy_utils.types.password.PasswordType(max_length=1137),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
